#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-or-later
// ---------------------------------------------------------------------------
// Building the file that goes in the spreadsheet.
//
//   node src/gas/build.js              write build/Code.gs
//   node src/gas/build.js --module     also write build/Code.mjs, importable
//
// The module form is how the tests get at it: the same generated text, with an
// export list bolted on, so what is exercised is the built artefact rather
// than the sources it came from. A build step nobody tests the output of is a
// place for a program to quietly become a different program.
// ---------------------------------------------------------------------------
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { bundle, orderFiles, withSubstitutes } from '../bundle.js';

export const ENTRY = '__gas.js';

/** What the spreadsheet build swaps out, and why it is safe to. */
export function substitutes(version, templates = [], directory = { entries: [] }) {
  return {
    // The menu is the entry: it pulls in the runner, and Google calls its
    // functions by name, so they have to survive as top-level declarations.
    [ENTRY]: "import './gas/menu.js';\n",
    // package.json is not there to read, and the version is fixed at build
    // time anyway — it describes the file being generated.
    'version.js': `export const VERSION = '${version}';\n`,
    // The templates are small and needed before any network call, so they
    // travel inside the file. The catalogue does not: it is most of the bulk,
    // and a copy made months ago should not be stuck with a months-old list of
    // employers, so that one is fetched.
    'templates-data.js': `export const TEMPLATES = ${JSON.stringify(templates, null, 1)};\n`,
    // The companies travel too. The first real run of this build found an
    // empty directory tab because the list was being fetched from a repository
    // that is private and answers 404 — so a tool that calls itself
    // self-contained now carries its own. The unlisted are left behind: they
    // exist to answer "why isn't X in here?" on the command line, and are a
    // third of the weight.
    'directory-data.js': `export const DIRECTORY = ${JSON.stringify({
      name: directory.name,
      description: directory.description,
      updated: directory.updated,
      entries: directory.entries,
    })};\n`,
  };
}

/** Names the spreadsheet's own functions call, and the tests reach for. */
export const EXPORTED = [
  'runWatch', 'recordRun', 'sheetClient', 'gasFetch', 'gasSleep',
  'readConfig', 'triage', 'planSync', 'ADAPTERS', 'TABS', 'readRange',
  'onOpen', 'menuWatch', 'menuSchedule', 'menuUnschedule', 'scheduledWatch',
  'parseHour', 'schedule', 'unschedule', 'scheduledHour',
  'runSetup', 'menuSetup', 'runDirectory', 'menuDirectory', 'catalogueUrl',
  'runTemplate', 'runFirstRun', 'templateNames', 'menuFirstRun',
  'runCheck', 'runSuggest', 'runLearn', 'runDiscover', 'sendDigest',
  'parseDestination', 'currentDestination', 'setDestination', 'menuNotifications',
  'menuCheck', 'menuSuggest', 'menuLearn', 'menuDiscover',
];

export function buildGas(read, { version = '0.0.0', templates = [], directory = { entries: [] } } = {}) {
  const withSubs = withSubstitutes(read, substitutes(version, templates, directory));
  const banner = [
    '// job-watch — generated by src/gas/build.js. Do not edit here.',
    `// version ${version}`,
    '//',
    '// Everything below is the same code the command line runs, flattened into',
    '// one scope because Apps Script has no modules, and stripped of async',
    '// because Apps Script has nothing to wait for.',
    '',
    '',
  ].join('\n');

  return {
    source: bundle(ENTRY, withSubs, { banner, sync: true }),
    files: orderFiles(ENTRY, withSubs).filter((f) => f !== ENTRY),
  };
}

// --- command line -----------------------------------------------------------
if (import.meta.url === `file://${process.argv[1]}`) {
  const root = fileURLToPath(new URL('../', import.meta.url));
  const read = (file) => readFileSync(path.join(root, file), 'utf8');
  const pkg = JSON.parse(readFileSync(fileURLToPath(new URL('../../package.json', import.meta.url)), 'utf8'));

  const templateDir = fileURLToPath(new URL('../../templates/', import.meta.url));
  const templates = readdirSync(templateDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => ({ id: f.replace(/\.json$/, ''), ...JSON.parse(readFileSync(path.join(templateDir, f), 'utf8')) }));

  const directory = JSON.parse(readFileSync(fileURLToPath(new URL('../../data/directory.json', import.meta.url)), 'utf8'));

  const { source, files } = buildGas(read, { version: pkg.version, templates, directory });
  // Two destinations. dist/ is committed and is what people paste into a
  // spreadsheet; build/ is scratch for the tests to import.
  const dist = fileURLToPath(new URL('../../dist/', import.meta.url));
  mkdirSync(dist, { recursive: true });
  writeFileSync(path.join(dist, 'Code.gs'), source);

  const out = fileURLToPath(new URL('../../build/', import.meta.url));
  mkdirSync(out, { recursive: true });
  writeFileSync(path.join(out, 'Code.gs'), source);

  if (process.argv.includes('--module')) {
    writeFileSync(path.join(out, 'Code.mjs'), `${source}\nexport { ${EXPORTED.join(', ')} };\n`);
  }

  console.log(`${files.length} files → dist/Code.gs`);
  console.log(`${source.split('\n').length} lines, ${Math.round(source.length / 1024)}KB`);
}
